import type { ProdukItem, ServiceItem, Business, Category } from './types';

// ============================================================
// Mock Data — untuk fallback / development tanpa Firebase
// ============================================================

export const mockAreas = [
  'Banjarsari Utara',
  'Banjarsari Selatan',
  'Banjarsari Barat',
  'Banjarsari Timur',
  'Tengah',
];

export const mockCategories: Category[] = [
  { category_id: '1', category_name: 'Makanan & Minuman', category_type: 'PRODUCT', slug: 'makanan', icon: '🍚', is_active: true },
  { category_id: '2', category_name: 'Kerajinan Tangan',  category_type: 'PRODUCT', slug: 'kerajinan', icon: '🧺', is_active: true },
  { category_id: '3', category_name: 'Camilan',           category_type: 'PRODUCT', slug: 'camilan', icon: '🥨', is_active: true },
  { category_id: '4', category_name: 'Pakaian & Fashion', category_type: 'PRODUCT', slug: 'fashion', icon: '👗', is_active: true },
  { category_id: '5', category_name: 'Jasa Reparasi',     category_type: 'SERVICE', slug: 'reparasi-elektronik', icon: '🔧', is_active: true },
  { category_id: '6', category_name: 'Kecantikan',        category_type: 'SERVICE', slug: 'kecantikan', icon: '💇', is_active: true },
  { category_id: '7', category_name: 'Pendidikan',        category_type: 'SERVICE', slug: 'pendidikan', icon: '📚', is_active: true },
  { category_id: '8', category_name: 'Pertanian',         category_type: 'PRODUCT', slug: 'pertanian', icon: '🌱', is_active: true },
];

export const mockBusinesses: Business[] = [
  {
    business_id:          'b1',
    business_name:        'Batik Sari Asih',
    business_logo_url:    null,
    business_description: 'Pengrajin batik tulis tradisional khas Banjarsari dengan motif unik warisan leluhur.',
    business_address:     'Jl. Melati No. 12, Banjarsari',
    business_phone:       '628123456789',
    slug:                 'batik-sari-asih',
    marketplace:          null,
    area_name:            'Banjarsari Utara',
    latitude:             null,
    longitude:            null,
    owner_name:           'Ibu Sri Wahyuni',
    is_active:            true,
    createdAt:            new Date(),
    updatedAt:            new Date(),
    deletedAt:            null,
  },
  {
    business_id:          'b2',
    business_name:        'Dapur Mak Inah',
    business_logo_url:    null,
    business_description: 'Produksi aneka masakan rumahan dan camilan tradisional. Tersedia untuk pesanan catering.',
    business_address:     'Jl. Kenanga No. 5, Banjarsari',
    business_phone:       '628234567890',
    slug:                 'dapur-mak-inah',
    marketplace:          null,
    area_name:            'Banjarsari Selatan',
    latitude:             null,
    longitude:            null,
    owner_name:           'Ibu Suminah',
    is_active:            true,
    createdAt:            new Date(),
    updatedAt:            new Date(),
    deletedAt:            null,
  },
  {
    business_id:          'b3',
    business_name:        'Servis Elektronik Pak Budi',
    business_logo_url:    null,
    business_description: 'Melayani servis berbagai jenis elektronik: HP, laptop, TV, kulkas, AC.',
    business_address:     'Jl. Anggrek No. 8, Banjarsari',
    business_phone:       '628345678901',
    slug:                 'servis-elektronik-pak-budi',
    marketplace:          null,
    area_name:            'Banjarsari Barat',
    latitude:             null,
    longitude:            null,
    owner_name:           'Budi Santoso',
    is_active:            true,
    createdAt:            new Date(),
    updatedAt:            new Date(),
    deletedAt:            null,
  },
];

export const mockProducts: ProdukItem[] = [
  {
    product_id:          'p1',
    business_id:         'b1',
    category_id:         '2',
    product_name:        'Batik Tulis Motif Parang',
    product_description: 'Kain batik tulis asli dengan motif parang khas Banjarsari. Dikerjakan oleh pengrajin berpengalaman.',
    product_price:       250000,
    slug:                'batik-tulis-motif-parang',
    whatsapp_number:     '628123456789',
    marketplace:         null,
    thumbnail_url:       null,
    tracking_active:     true,
    is_active:           true,
    createdAt:           new Date(),
    updatedAt:           new Date(),
    deletedAt:           null,
  },
  {
    product_id:          'p2',
    business_id:         'b2',
    category_id:         '1',
    product_name:        'Tempe Mendoan Crispy',
    product_description: 'Mendoan crispy homemade dengan bumbu rahasia. Cocok untuk camilan atau lauk makan.',
    product_price:       15000,
    slug:                'tempe-mendoan-crispy',
    whatsapp_number:     '628234567890',
    marketplace:         null,
    thumbnail_url:       null,
    tracking_active:     true,
    is_active:           true,
    createdAt:           new Date(),
    updatedAt:           new Date(),
    deletedAt:           null,
  },
  {
    product_id:          'p3',
    business_id:         'b2',
    category_id:         '3',
    product_name:        'Kripik Singkong Pedas Manis',
    product_description: 'Kripik singkong renyah dengan varian rasa pedas manis khas Jawa Tengah.',
    product_price:       20000,
    slug:                'kripik-singkong-pedas-manis',
    whatsapp_number:     '628234567890',
    marketplace:         null,
    thumbnail_url:       null,
    tracking_active:     true,
    is_active:           true,
    createdAt:           new Date(),
    updatedAt:           new Date(),
    deletedAt:           null,
  },
  {
    product_id:          'p4',
    business_id:         'b1',
    category_id:         '2',
    product_name:        'Batik Cap Motif Truntum',
    product_description: 'Batik cap premium dengan motif truntum. Bahan katun halus, nyaman dipakai.',
    product_price:       180000,
    slug:                'batik-cap-motif-truntum',
    whatsapp_number:     '628123456789',
    marketplace:         null,
    thumbnail_url:       null,
    tracking_active:     true,
    is_active:           true,
    createdAt:           new Date(),
    updatedAt:           new Date(),
    deletedAt:           null,
  },
];

export const mockServices: ServiceItem[] = [
  {
    service_id:          's1',
    business_id:         'b3',
    category_id:         '5',
    service_name:        'Servis HP & Smartphone',
    service_description: 'Perbaikan HP semua merek: ganti layar, baterai, charger, software. Bergaransi 30 hari.',
    minimum_price:       50000,
    maximum_price:       350000,
    price_type:          'RANGE',
    is_negotiable:       true,
    whatsapp_number:     '628345678901',
    marketplace:         null,
    availability_type:   'ALWAYS_AVAILABLE',
    slug:                'servis-hp-smartphone',
    is_active:           true,
    createdAt:           new Date(),
    updatedAt:           new Date(),
    deletedAt:           null,
  },
  {
    service_id:          's2',
    business_id:         'b3',
    category_id:         '5',
    service_name:        'Servis Laptop & Komputer',
    service_description: 'Install ulang OS, bersih virus, upgrade RAM/SSD, ganti keyboard/LCD laptop.',
    minimum_price:       100000,
    maximum_price:       500000,
    price_type:          'RANGE',
    is_negotiable:       true,
    whatsapp_number:     '628345678901',
    marketplace:         null,
    availability_type:   'BY_SCHEDULE',
    slug:                'servis-laptop-komputer',
    is_active:           true,
    createdAt:           new Date(),
    updatedAt:           new Date(),
    deletedAt:           null,
  },
  {
    service_id:          's3',
    business_id:         'b2',
    category_id:         '1',
    service_name:        'Katering Nasi Box Rumahan',
    service_description: 'Layanan katering nasi box untuk acara arisan, rapat, atau hajatan. Min. order 20 box.',
    minimum_price:       15000,
    maximum_price:       35000,
    price_type:          'RANGE',
    is_negotiable:       false,
    whatsapp_number:     '628234567890',
    marketplace:         null,
    availability_type:   'BY_REQUEST',
    slug:                'katering-nasi-box',
    is_active:           true,
    createdAt:           new Date(),
    updatedAt:           new Date(),
    deletedAt:           null,
  },
];
