import type { Product, Service, Business, Category } from './types';

// ============================================================
// Mock Data — untuk fallback / development tanpa Firebase
// ============================================================

export const mockAreas = [
  'Banjarsari Utara',
  'Banjarsari Selatan',
  'Banjarsari Barat',
  'Banjarsari Timur',
  'Tengah',
];

export const mockCategories: Category[] = [
  { id: '1', name: 'Makanan & Minuman', slug: 'makanan', icon: '🍚', type: 'product' },
  { id: '2', name: 'Kerajinan Tangan', slug: 'kerajinan', icon: '🧺', type: 'product' },
  { id: '3', name: 'Camilan', slug: 'camilan', icon: '🥨', type: 'product' },
  { id: '4', name: 'Pakaian & Fashion', slug: 'fashion', icon: '👗', type: 'product' },
  { id: '5', name: 'Jasa Reparasi', slug: 'reparasi-elektronik', icon: '🔧', type: 'service' },
  { id: '6', name: 'Kecantikan', slug: 'kecantikan', icon: '💇', type: 'service' },
  { id: '7', name: 'Pendidikan', slug: 'pendidikan', icon: '📚', type: 'service' },
  { id: '8', name: 'Pertanian', slug: 'pertanian', icon: '🌱', type: 'product' },
];

export const mockBusinesses: Business[] = [
  {
    id: 'b1',
    name: 'Batik Sari Asih',
    owner: 'Ibu Sri Wahyuni',
    description: 'Pengrajin batik tulis tradisional khas Banjarsari dengan motif unik warisan leluhur.',
    category: 'kerajinan',
    address: 'Jl. Melati No. 12, Banjarsari',
    area: 'Banjarsari Utara',
    whatsapp: '628123456789',
    imageUrl: '',
    status: 'aktif',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'b2',
    name: 'Dapur Mak Inah',
    owner: 'Ibu Suminah',
    description: 'Produksi aneka masakan rumahan dan camilan tradisional. Tersedia untuk pesanan catering.',
    category: 'makanan',
    address: 'Jl. Kenanga No. 5, Banjarsari',
    area: 'Banjarsari Selatan',
    whatsapp: '628234567890',
    imageUrl: '',
    status: 'aktif',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'b3',
    name: 'Servis Elektronik Pak Budi',
    owner: 'Budi Santoso',
    description: 'Melayani servis berbagai jenis elektronik: HP, laptop, TV, kulkas, AC.',
    category: 'reparasi-elektronik',
    address: 'Jl. Anggrek No. 8, Banjarsari',
    area: 'Banjarsari Barat',
    whatsapp: '628345678901',
    imageUrl: '',
    status: 'aktif',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockProducts: Product[] = [
  {
    id: 'p1',
    name: 'Batik Tulis Motif Parang',
    description: 'Kain batik tulis asli dengan motif parang khas Banjarsari. Dikerjakan oleh pengrajin berpengalaman.',
    price: 250000,
    category: 'kerajinan',
    businessId: 'b1',
    imageUrls: [],
    status: 'aktif',
    clickCount: 487,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'p2',
    name: 'Tempe Mendoan Crispy',
    description: 'Mendoan crispy homemade dengan bumbu rahasia. Cocok untuk camilan atau lauk makan.',
    price: 15000,
    category: 'makanan',
    businessId: 'b2',
    imageUrls: [],
    status: 'aktif',
    clickCount: 342,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'p3',
    name: 'Kripik Singkong Pedas Manis',
    description: 'Kripik singkong renyah dengan varian rasa pedas manis khas Jawa Tengah.',
    price: 20000,
    category: 'camilan',
    businessId: 'b2',
    imageUrls: [],
    status: 'aktif',
    clickCount: 278,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 'p4',
    name: 'Batik Cap Motif Truntum',
    description: 'Batik cap premium dengan motif truntum. Bahan katun halus, nyaman dipakai.',
    price: 180000,
    category: 'kerajinan',
    businessId: 'b1',
    imageUrls: [],
    status: 'aktif',
    clickCount: 195,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockServices: Service[] = [
  {
    id: 's1',
    name: 'Servis HP & Smartphone',
    description: 'Perbaikan HP semua merek: ganti layar, baterai, charger, software. Bergaransi 30 hari.',
    priceRange: 'Rp 50.000 – Rp 350.000',
    price: 50000,
    category: 'reparasi-elektronik',
    businessId: 'b3',
    imageUrls: [],
    status: 'aktif',
    clickCount: 312,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 's2',
    name: 'Servis Laptop & Komputer',
    description: 'Install ulang OS, bersih virus, upgrade RAM/SSD, ganti keyboard/LCD laptop.',
    priceRange: 'Rp 100.000 – Rp 500.000',
    price: 100000,
    category: 'reparasi-elektronik',
    businessId: 'b3',
    imageUrls: [],
    status: 'aktif',
    clickCount: 241,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 's3',
    name: 'Katering Nasi Box Rumahan',
    description: 'Layanan katering nasi box untuk acara arisan, rapat, atau hajatan. Min. order 20 box.',
    priceRange: 'Rp 15.000 – Rp 35.000 / box',
    price: 15000,
    category: 'makanan',
    businessId: 'b2',
    imageUrls: [],
    status: 'aktif',
    clickCount: 178,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
